# Development environment values for video-to-podcast
# This file provides configuration suitable for development/testing

# Global configuration for local registry
global:
  imageRegistry: "registry.localhost:5000"
  imagePullSecrets: []

# Use NodePort services for easy access during development
api:
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  
  # Lower resource requirements for development
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
  
  # Development-friendly configuration
  config:
    database:
      connectionString: ":memory:"  # In-memory for quick testing
    storage:
      basePath: "/tmp/video-to-podcast"  # Temporary storage

ui:
  service:
    type: NodePort
    port: 3000
    nodePort: 30300
  
  # Lower resource requirements for development
  resources:
    limits:
      memory: 256Mi
      cpu: 250m
    requests:
      memory: 128Mi
      cpu: 100m

# Enable ingress with development hostname
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: video-to-podcast.dev.local
      paths:
        - path: /
          pathType: Prefix
          service: ui
        - path: /v1
          pathType: Prefix
          service: api

# Disable persistence for development (faster startup)
persistence:
  enabled: false

# Disable autoscaling for development
autoscaling:
  api:
    enabled: false
  ui:
    enabled: false

# Enable monitoring for development testing
monitoring:
  serviceMonitor:
    enabled: false  # Set to true if you have Prometheus operator

# Relaxed security for development
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0

securityContext:
  runAsNonRoot: false
  runAsUser: 0

# Development annotations
podAnnotations:
  environment: "development"
  
podLabels:
  environment: "development"
