apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-to-podcast.fullname" . }}-config
  labels:
    {{- include "video-to-podcast.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "video-to-podcast.api.config" . | nindent 4 }}
    {{- include "video-to-podcast.ui.config" . | nindent 4 }}
