{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "video-to-podcast.fullname" . }}
  labels:
    {{- include "video-to-podcast.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "video-to-podcast.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from ingress controller
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.api.service.targetPort }}
        - protocol: TCP
          port: {{ .Values.ui.service.targetPort }}
    # Allow UI to communicate with API
    - from:
        - podSelector:
            matchLabels:
              {{- include "video-to-podcast.ui.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.api.service.targetPort }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS for downloading videos
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    # Allow API to communicate with UI (if needed)
    - to:
        - podSelector:
            matchLabels:
              {{- include "video-to-podcast.ui.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.ui.service.targetPort }}
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
