apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-to-podcast.api.serviceName" . }}
  labels:
    {{- include "video-to-podcast.api.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "video-to-podcast.api.selectorLabels" . | nindent 4 }}
