apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: podcastcluster # (will still be prefixed with `k3d-`)
servers: 1
agents: 1
ports:
  - port: 8080:80 # map port 8080 on host to port 80 on loadbalancer (Traefik)
    nodeFilters:
      - loadbalancer
  - port: 8081:8081 # map port 8081 on host to port 8081 on loadbalancer (for our app)
    nodeFilters:
      - loadbalancer
kubeAPI:
  # setting port and IP on Windows explicitly as the default k3d port can lead to kubectl not being able to connect
  hostIP: "127.0.0.1"
  hostPort: "6550"
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
