apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: video-podcast-cluster
servers: 1
agents: 1
ports:
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 3000:3000
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"