# New images are release just by adding a new tag
name: Release Images
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# Defines environment variables for the workflow
env:
  REGISTRY: ghcr.io

# Build and push both API and UI service images using matrix strategy
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - name: api
            dockerfile: Dockerfile.api
          - name: ui
            dockerfile: Dockerfile.ui
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for ${{ matrix.service.name }} Docker image
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.service.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
            
      - name: Build and push ${{ matrix.service.name }} Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.service.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}