on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7

      - name: Run tests (Docker)
        if: matrix.platform == 'ubuntu-latest'
        run: docker build --target test .

      - name: Install Go
        if: matrix.platform == 'windows-latest'
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.x"

      - name: Install ffmpeg (Windows)
        if: matrix.platform == 'windows-latest'
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Run tests (Windows)
        if: matrix.platform == 'windows-latest'
        run: go test -short ./...
